# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1_m2lCbM30IiNmdcsPMqCfS3zOqATAR8t
"""

from google.colab import drive
drive.mount('/content/drive')

import pandas as pd
import numpy as np
data=pd.read_csv('/content/drive/MyDrive/ws.csv')
c=np.array(data)[:,:-1]
t=np.array(data)[:,-1]
print(c)
print(t)

def train(c,t):
    for i, v in enumerate(t):
        if v == "Yes":
            spec_hyp=c[i].copy()
            break 
    for i, v in enumerate(c):
        if t[i] == "Yes":
            for x in range(len(spec_hyp)):
                if v[x] != spec_hyp[x]:
                    spec_hyp[x] = '?'
                else:
                    pass 
    return spec_hyp 

print("\n Final Hypothesis is ",train(c,t))